const USER_ROLES = {
    ADMIN: "ADMIN",
    VENDOR: "VENDOR",
    REVIEWER: "REVIEWER"
};

const VENDOR_STATUS = {
    PENDING_VERIFICATION: "PENDING_VERIFICATION",
    UNDER_REVIEW: "UNDER_REVIEW",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    ACTIVE: "ACTIVE",
    COMPLIANCE_FAILED: "COMPLIANCE_FAILED",
    RENEWAL_REQUIRED: "RENEWAL_REQUIRED"
};

const DOCUMENT_STATUS = {
    VALID: "VALID",
    EXPIRING_SOON: "EXPIRING_SOON",
    EXPIRED: "EXPIRED",
    REJECTED: "REJECTED"
};

const DOCUMENT_TYPES = {
    GST_CERTIFICATE: "GST_CERTIFICATE",
    BUSINESS_LICENSE: "BUSINESS_LICENSE",
    INSURANCE: "INSURANCE",
    TAX_DOCUMENT: "TAX_DOCUMENT",
    BANK_DOCUMENT: "BANK_DOCUMENT"
};

const REVIEW_DECISION = {
    APPROVED: "APPROVED",
    REJECTED: "REJECTED"
};

const RISK_LEVEL = {
    LOW: "LOW",
    MEDIUM: "MEDIUM",
    HIGH: "HIGH"
};

export {
    USER_ROLES,
    VENDOR_STATUS,
    DOCUMENT_STATUS,
    DOCUMENT_TYPES,
    REVIEW_DECISION,
    RISK_LEVEL
};